/*
 * SbApp: Open Source software for novelists and authors.
 * Original idea 2008 - 2012 Martin Mustun
 * Copyrigth (C) Favdb
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
package storybook.ui.dialog.edit;

import static storybook.ui.dialog.edit.CommonBox.loadCbCities;
import static storybook.ui.dialog.edit.CommonBox.loadCbCountries;
import static storybook.ui.dialog.edit.CommonBox.loadCbSites;
import static storybook.ui.dialog.edit.DlgErrorMessage.mandatoryField;

import java.awt.CardLayout;

import storybook.model.hbn.entity.Location;
import storybook.toolkit.swing.htmleditor.HtmlEditor;

/**
 *
 * @author favdb
 */
public class EditLocation extends javax.swing.JPanel {

    Editor parent;
    Location location;
    private final CardLayout cardDescription = new CardLayout(0, 0);
    private final CardLayout cardNotes = new CardLayout(0, 0);
    private final HtmlEditor description = new HtmlEditor();
    private final HtmlEditor notes = new HtmlEditor();

    /**
     * Creates new form EditLocation
     */
    public EditLocation() {
        initComponents();
    }

    public EditLocation(Editor m, Location l) {
        initComponents();
        parent = m;
        location = l;
        initUI();
    }

    private void initUI() {
        paneDescription.setLayout(cardDescription);
        paneDescription.add(description, "description");
        cardDescription.show(paneDescription, "description");
        paneNotes.setLayout(cardNotes);
        paneNotes.add(notes);
        cardNotes.show(paneNotes, "notes");
        if (location == null) {
            location = createNewLocation();
        }
        txtId.setText(Long.toString(location.getId()));
        txName.setText(location.getName());
        txAdress.setText(location.getAddress());
        loadCbCities(parent.mainFrame, cbCity, location);
        loadCbCountries(parent.mainFrame, cbCountry, location);
        loadCbSites(parent.mainFrame, cbSite, location);
        if (location.getAltitude()!=null) txAltitude.setText("" + location.getAltitude());
        description.setText(location.getDescription());
        notes.setText(location.getNotes());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        paneCommon = new javax.swing.JPanel();
        lbId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lbTitle = new javax.swing.JLabel();
        txName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txAdress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbCity = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        cbCountry = new javax.swing.JComboBox<String>();
        jLabel35 = new javax.swing.JLabel();
        cbSite = new javax.swing.JComboBox<Location>();
        jLabel4 = new javax.swing.JLabel();
        txAltitude = new javax.swing.JTextField();
        paneDescription = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        paneNotes = new javax.swing.JPanel();

        setBorder(null);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("storybook/msg/messages"); // NOI18N
        lbId.setText(bundle.getString("msg.common.id")); // NOI18N

        txtId.setEditable(false);

        lbTitle.setText(bundle.getString("msg.common.name")); // NOI18N

        jLabel1.setText(bundle.getString("msg.common.adress")); // NOI18N

        jLabel2.setText(bundle.getString("msg.common.city")); // NOI18N

        jLabel3.setText(bundle.getString("msg.common.country")); // NOI18N

        jLabel35.setText(bundle.getString("msg.common.site")); // NOI18N

        jLabel4.setText(bundle.getString("msg.common.altitude")); // NOI18N

        paneDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("msg.common.description"))); // NOI18N

        javax.swing.GroupLayout paneDescriptionLayout = new javax.swing.GroupLayout(paneDescription);
        paneDescription.setLayout(paneDescriptionLayout);
        paneDescriptionLayout.setHorizontalGroup(
            paneDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paneDescriptionLayout.setVerticalGroup(
            paneDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/clear.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/clear.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/clear.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout paneCommonLayout = new javax.swing.GroupLayout(paneCommon);
        paneCommon.setLayout(paneCommonLayout);
        paneCommonLayout.setHorizontalGroup(
            paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCommonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCommonLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(paneCommonLayout.createSequentialGroup()
                        .addGroup(paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel35)
                            .addComponent(lbTitle)
                            .addComponent(lbId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneCommonLayout.createSequentialGroup()
                                .addComponent(txtId)
                                .addGap(281, 281, 281))
                            .addGroup(paneCommonLayout.createSequentialGroup()
                                .addGroup(paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txName)
                                    .addComponent(txAdress)
                                    .addGroup(paneCommonLayout.createSequentialGroup()
                                        .addGroup(paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(paneCommonLayout.createSequentialGroup()
                                                 .addComponent(cbSite, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                 .addComponent(jButton3))
                                            .addGroup(paneCommonLayout.createSequentialGroup()
                                                .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2))
                                            .addGroup(paneCommonLayout.createSequentialGroup()
                                                .addComponent(cbCity, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1)))
                                        .addGap(0, 87, Short.MAX_VALUE)))
                                .addContainerGap())))))
            .addComponent(paneDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneCommonLayout.setVerticalGroup(
            paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCommonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitle)
                    .addComponent(txName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton2)
                    .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton3)
                    .addComponent(cbSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneCommonLayout.createSequentialGroup()
                .addGroup(paneCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCommonLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel2))
                    .addGroup(paneCommonLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel3))
                        .addGroup(paneCommonLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel35)))
                .addGap(265, 265, 265))
        );

        jTabbedPane1.addTab(bundle.getString("msg.common"), paneCommon); // NOI18N

        javax.swing.GroupLayout paneNotesLayout = new javax.swing.GroupLayout(paneNotes);
        paneNotes.setLayout(paneNotesLayout);
        paneNotesLayout.setHorizontalGroup(
            paneNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        paneNotesLayout.setVerticalGroup(
            paneNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(bundle.getString("msg.common.notes"), paneNotes); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCity;
    private javax.swing.JComboBox<String> cbCountry;
    private javax.swing.JComboBox<Location> cbSite;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel paneCommon;
    private javax.swing.JPanel paneDescription;
    private javax.swing.JPanel paneNotes;
    private javax.swing.JTextField txAdress;
    private javax.swing.JTextField txAltitude;
    private javax.swing.JTextField txName;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

    private Location createNewLocation() {
        Location l = new Location("", "", "", "", 0, "", "", null);
        l.setId(-1L);
        return l;
    }

    public boolean isModified() {
        if (!txName.getText().equals(location.getName())) return(true);
        if (!txAdress.getText().equals(location.getAddress())) return(true);
        if (!cbCity.getSelectedItem().toString().equals(location.getCity())) return(true);
        if (!cbCountry.getSelectedItem().toString().equals(location.getCountry())) return(true);
        if (!cbSite.getSelectedItem().equals(location.getSite())) return(true);
        if (!txAltitude.getText().equals(location.getAltitude())) return(true);
        if (!description.getText().equals(location.getDescription())) return(true);
        if (!notes.getText().equals(location.getNotes())) return (true);
	return(false)
;    }

    public String saveData() {
        String rt = ctrlData();
        if ("".equals(rt)) {
            location.setName(txName.getText());
			location.setAddress(txAdress.getText());
			location.setCity(cbCity.getSelectedItem().toString());
			location.setCountry(cbCountry.getSelectedItem().toString());
			location.setSite((Location)cbSite.getSelectedItem());
			location.setAltitude(Integer.getInteger(txAltitude.getText()));
			location.setDescription(description.getText());
			location.setNotes(notes.getText());
        }
        return (rt);
    }

    private String ctrlData() {
        if (!txName.getText().equals("")) return(mandatoryField("msg.common.name"));
        return ("");
    }
}
