/*
 * SbApp: Open Source software for novelists and authors.
 * Original idea 2008 - 2012 Martin Mustun
 * Copyrigth (C) Favdb
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
package storybook.ui.dialog.edit;

import java.awt.CardLayout;
import java.awt.Color;
import storybook.model.hbn.entity.Strand;
import storybook.toolkit.I18N;
import storybook.toolkit.swing.htmleditor.HtmlEditor;
import storybook.ui.dialog.chooser.DlgColorChooser;
import static storybook.ui.dialog.edit.DlgErrorMessage.mandatoryField;

/**
 *
 * @author favdb
 */
public class EditStrand extends javax.swing.JPanel {

	Editor parent;
	Strand strand;
	private final CardLayout card = new CardLayout(0, 0);
	private final HtmlEditor notes = new HtmlEditor();

	/**
	 * Creates new form EditStrand
	 */
	public EditStrand() {
		initComponents();
	}

	public EditStrand(Editor m, Strand s) {
		initComponents();
		parent = m;
		strand = s;
		initUI();
	}

	private void initUI() {
		paneNotes.setLayout(card);
		paneNotes.add(notes, "Notes");
		card.show(paneNotes, "Notes");
		if (strand == null) {
			strand = new Strand();
			strand.setId(-1l);
			return;
		}
		txtID.setText(Long.toString(strand.getId()));
		txtName.setText(strand.getName());
		txAbbreviation.setText(strand.getAbbreviation());
		txColor.setBackground(strand.getJColor());
		txOrder.setText((Integer.toString(strand.getSort())));
		notes.setText(strand.getNotes());
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbId = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbAbbreviation = new javax.swing.JLabel();
        txAbbreviation = new javax.swing.JTextField();
        lbColor = new javax.swing.JLabel();
        txColor = new javax.swing.JTextField();
        btColor = new javax.swing.JButton();
        lbOrder = new javax.swing.JLabel();
        txOrder = new javax.swing.JTextField();
        paneNotes = new javax.swing.JPanel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("storybook/msg/messages"); // NOI18N
        lbId.setText(bundle.getString("msg.common.id")); // NOI18N

        txtID.setEditable(false);
        txtID.setText(" ");

        lbName.setText(bundle.getString("msg.common.name")); // NOI18N

        lbAbbreviation.setText(bundle.getString("msg.common.abbreviation")); // NOI18N

        txAbbreviation.setText(" ");

        lbColor.setText(bundle.getString("msg.common.color")); // NOI18N

        txColor.setEditable(false);

        btColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storybook/resources/icons/16x16/palette.png"))); // NOI18N
        btColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorActionPerformed(evt);
            }
        });

        lbOrder.setText(bundle.getString("msg.common.order")); // NOI18N

        paneNotes.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("msg.common.notes"))); // NOI18N
        paneNotes.setPreferredSize(new java.awt.Dimension(418, 312));

        javax.swing.GroupLayout paneNotesLayout = new javax.swing.GroupLayout(paneNotes);
        paneNotes.setLayout(paneNotesLayout);
        paneNotesLayout.setHorizontalGroup(
            paneNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paneNotesLayout.setVerticalGroup(
            paneNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName)
                    .addComponent(lbId)
                    .addComponent(lbAbbreviation)
                    .addComponent(lbColor)
                    .addComponent(lbOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txColor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btColor))
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txAbbreviation, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 310, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(paneNotes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAbbreviation)
                    .addComponent(txAbbreviation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btColor)
                    .addComponent(lbColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOrder)
                    .addComponent(txOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btColorActionPerformed
		DlgColorChooser dlg = new DlgColorChooser(this.parent, Color.GRAY);
		dlg.setVisible(true);
		strand.setJColor(dlg.myColor);
    }//GEN-LAST:event_btColorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btColor;
    private javax.swing.JLabel lbAbbreviation;
    private javax.swing.JLabel lbColor;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbOrder;
    private javax.swing.JPanel paneNotes;
    private javax.swing.JTextField txAbbreviation;
    private javax.swing.JTextField txColor;
    private javax.swing.JTextField txOrder;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

	public void set(Strand s) {
		strand = s;
		initUI();
	}

	boolean isModified() {
		if (!txtName.getText().equals(strand.getName()))
			return (true);
		if (!txAbbreviation.getText().equals(strand.getAbbreviation()))
			return (true);
		if (!txColor.getBackground().equals(strand.getJColor()))
			return (true);
		if (!txOrder.getText().equals((Integer.toString(strand.getSort()))))
			return (true);
		if (!notes.getText().equals(strand.getNotes()))
			return (true);
		return (false);
	}

	public String saveData() {
		String rt = ctrlData();
		if ("".equals(rt)) {
			strand.setName(txtName.getText());
			strand.setAbbreviation(txAbbreviation.getText());
			strand.setJColor(txColor.getBackground());
			strand.setSort(Integer.getInteger(txOrder.getText()));
			strand.setNotes(notes.getText());
		}
		return (rt);
	}

	private String ctrlData() {
		String rt = "";
		if (txtName.getText().isEmpty())
			return (mandatoryField("msg.common.name"));
		if (txAbbreviation.getText().isEmpty())
			return (mandatoryField("msg.common.abbreviation"));
		return (rt);
	}
}
