/*
 * SbApp: Open Source software for novelists and authors.
 * Original idea 2008 - 2012 Martin Mustun
 * Copyrigth (C) Favdb
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
package storybook.ui.dialog.edit;

/**
 *
 * @author favdb
 */
public class HtmlEditorPane extends javax.swing.JPanel {
	private static final String INVALID_TAGS[] = {"html", "head", "body", "title"};

	/**
	 * Creates new form HtmlEditorPane
	 */
	public HtmlEditorPane() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbFormatParagraph = new javax.swing.JComboBox();
        cbFonts = new javax.swing.JComboBox();
        btFontSize = new javax.swing.JButton();
        btFontColor = new javax.swing.JButton();
        btItalic = new javax.swing.JButton();
        btUnderline = new javax.swing.JButton();
        btList = new javax.swing.JButton();
        btListNum = new javax.swing.JButton();
        btAlignLeft = new javax.swing.JButton();
        btAlignCenter = new javax.swing.JButton();
        btAlignRight = new javax.swing.JButton();
        btAlignJustify = new javax.swing.JButton();
        btLink = new javax.swing.JButton();
        btImage = new javax.swing.JButton();
        btTable = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        paneText = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        paneHtml = new javax.swing.JEditorPane();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbFormatParagraph.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFormatParagraph.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbFonts.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFonts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btFontSize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/fontsize.png"))); // NOI18N
        btFontSize.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btFontSize.setFocusable(false);
        btFontSize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFontSize.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btFontColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/color.png"))); // NOI18N
        btFontColor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btFontColor.setFocusable(false);
        btFontColor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFontColor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btItalic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/italic.png"))); // NOI18N
        btItalic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/underline.png"))); // NOI18N
        btUnderline.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/listunordered.png"))); // NOI18N
        btList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btListNum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/listordered.png"))); // NOI18N
        btListNum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btAlignLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/al_left.png"))); // NOI18N
        btAlignLeft.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btAlignCenter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/al_center.png"))); // NOI18N
        btAlignCenter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btAlignRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/al_right.png"))); // NOI18N
        btAlignRight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btAlignJustify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/al_just.png"))); // NOI18N
        btAlignJustify.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/link.png"))); // NOI18N
        btLink.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/image.png"))); // NOI18N
        btImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/table.png"))); // NOI18N
        btTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shef/ui/resources/images/x16/bold.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btItalic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btUnderline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btListNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlignLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlignCenter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlignRight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlignJustify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTable))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbFormatParagraph, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFonts, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btFontSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btFontColor)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbFormatParagraph, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbFonts, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFontColor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btItalic)
                            .addComponent(btUnderline))
                        .addComponent(btList, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btListNum, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btAlignLeft, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btAlignCenter, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btAlignRight))
                    .addComponent(btAlignJustify, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btLink)
                    .addComponent(btImage)
                    .addComponent(btTable)
                    .addComponent(jButton1)))
        );

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jScrollPane1.setViewportView(paneText);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("storybook/resources/messages"); // NOI18N
        jTabbedPane1.addTab(bundle.getString("msg.common.text"), jScrollPane1); // NOI18N

        jScrollPane2.setViewportView(paneHtml);

        jTabbedPane1.addTab(bundle.getString("msg.common.html"), jScrollPane2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlignCenter;
    private javax.swing.JButton btAlignJustify;
    private javax.swing.JButton btAlignLeft;
    private javax.swing.JButton btAlignRight;
    private javax.swing.JButton btFontColor;
    private javax.swing.JButton btFontSize;
    private javax.swing.JButton btImage;
    private javax.swing.JButton btItalic;
    private javax.swing.JButton btLink;
    private javax.swing.JButton btList;
    private javax.swing.JButton btListNum;
    private javax.swing.JButton btTable;
    private javax.swing.JButton btUnderline;
    private javax.swing.JComboBox cbFonts;
    private javax.swing.JComboBox cbFormatParagraph;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JEditorPane paneHtml;
    private javax.swing.JEditorPane paneText;
    // End of variables declaration//GEN-END:variables

	public void setText(String txt) {
		paneText.setText(txt);
	}
}
