#!/bin/sh -e

if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/oStorybook-icon.png
fi

if [ -x "`which update-mime-database 2>/dev/null`" ]; then
	update-mime-database /usr/share/mime
fi

if [ -x "`which update-menus 2>/dev/null`" ]; then
    update-menus ;
fi
				
